### ISSUE TITLE
java descypt method call failed

### ISSUE THREAD

**Issue by 15626131368** [google/tink#112]
hi,it is ok to call encrypt method,but when i call the decrypt method,is always throws GeneralSecurityException,below is my code:
public String decrypt(String ciphertext) {
        String result = null;
        try {
            byte[] plaintext = aead.decrypt(ciphertext.getBytes() , null);
            result = plaintext.toString();
        } catch (GeneralSecurityException e) {
            e.printStackTrace();
        }
        return result;
    }

**Comment by thaidn** [comment]
Hi there,

Can you show us your full program and stack trace?

**Comment by DthFish** [comment]
@15626131368 https://github.com/DthFish/HencoderDemo/blob/master/app/src/main/java/com/dthfish/hencoderdemo/TinkManager.java
我这样用，你看下 toHex 和 toByte 两个方法的调用，可能你犯和和我之前一样的错误

**Comment by thaidn** [comment]
I see no obvious flaw. Two suggestions:

1/ Have you tested toHex and toByte? Instead of hex, you can use Base64 encoding with https://developer.android.com/reference/android/util/Base64.

2/ Use https://github.com/google/tink/blob/master/java/src/main/java/com/google/crypto/tink/integration/android/AndroidKeysetManager.java to manage keysets on Android.

**Comment by DthFish** [comment]
@thaidn Thank you for your suggestions!

**Comment by thaidn** [comment]
Have you figured out the issue?

**Comment by thaidn** [comment]
Please reopen if you have any other questions.
