### ISSUE TITLE
How to export public key?

### ISSUE THREAD

**Issue by evalsinca** [google/tink#124]
I have read the documentation and code as best as I can but am still struggling with some basics that seem rather easy with other crypto libraries (Bouncy Castle, default Java, etc.).   For example, imagine that an iOS/Android app generates a key pair using Tink.  

```
KeysetHandle ksh = KeysetHandle.generateNew(
			        HybridKeyTemplates.ECIES_P256_HKDF_HMAC_SHA256_AES128_GCM);
```

How then to send the public key generated to the server where it may be used to encrypt data intended for the user?   There seems no obvious way looking at the code.  The only kludgy work-around I have come up with is as follows:

`String str = writeKeyToString(ksh.getPublicKeysetHandle());`

where the writeKeyString() method uses CleartextKeysetHandle's write method to write the public key as a Json set of bytes using the JsonKeysetWriter which we then send to server after Base64 encoding the bytes.

I am sure I am missing something - that an easier and cleaner method lurks.   Hoping someone can clear this up...

Thanks!

**Comment by thaidn** [comment]
You got it right. It's a bit clumsy because we want to encourage users to store keysets encrypted at rest and we also want to support different keyset formats.

Sorry about that! Do you have any suggestions to simplify it?

**Comment by evalsinca** [comment]
@thaidn - thank you, and sorry if I came across as complaining.  That was not my intent.  My solution is to use the method I outlined above.  Is this correct (it works, I know, because I tried it - but I know in crypto - where I am not expert - that correctness is subtle)?

Thanks for an awesome library!

**Comment by thaidn** [comment]
No, you didn't come across as complaining :).

What you're doing is correct. Since Tinkey [1] is the key management tool, I recommend reviewing its source code if you're not sure if you're using the key management APIs correctly. Of course you can always file a bug or drop us a line at tink-users@googlegroups.com.

We're glad that you found the library useful!

[1] https://github.com/google/tink/tree/master/tools/tinkey/src/main/java/com/google/crypto/tink/tinkey

**Comment by evalsinca** [comment]
Thanks @thaidn !  Will do.

**Comment by piotrblasiak** [comment]
Is writing to JSON, parsing the JSON and then taking it from there still the only way to do this? I think some other way of doing this should be possible - especially considering most people already have a framework that serialises to JSON (spring etc) so that JSON string isn't of much use and just pure overhead.

Piotr
