### ISSUE TITLE
Execution time for AES GCM with larger files in Tink is to high

### ISSUE THREAD

**Issue by java-crypto** [google/tink#174]
Hi team,
I tested the encryption & decryption times for large files using AES GCM with Standard Java JRE, Google Tink and Bouncy Castle.
As Tink seems to use the underlying JRE-provider for GCM the times (JRE-Tink) are nearly identical but Bouncy Castle is a lot faster than JRE/Tink.

Using of much larger files than 20mb will get JRE or Tink GCM-encryption unusable on decryption side. As BouncyCastle shows there is a real chance to fasten the decryption :-)

Are there any plans to change the implementation ?

Here are my measures:

GCM Encryption / Decryption with JRE
Round	Filename	Enc	Dec
1	E:\t_1mb.dat	23	297
2	E:\t_2mb.dat	47	516
3	E:\t_3mb.dat	63	859
4	E:\t_4mb.dat	78	1500
5	E:\t_5mb.dat	93	2297

GCM Encryption / Decryption with TINK
Round	Filename	Enc	Dec
1	E:\t_1mb.dat	31	110
2	E:\t_2mb.dat	31	407
3	E:\t_3mb.dat	62	875
4	E:\t_4mb.dat	78	1484
5	E:\t_5mb.dat	93	2297

GCM Encryption / Decryption with BC
Round	Filename	Enc	Dec
1	E:\t_1mb.dat	31	31
2	E:\t_2mb.dat	32	31
3	E:\t_3mb.dat	47	47
4	E:\t_4mb.dat	62	63
5	E:\t_5mb.dat	78	78

Sourcecode is available at: https://github.com/java-crypto/TinkTest/blob/master/EncryptionGcmJreTinkBc.java
Versions used: jre java 8 update 191, bouncycastle: bcprov-jdk15on-160.jar, tink: tink-1.2.1.jar & protobuf-java-3.6.1.jar

Kind regards, Michael
[EncryptionGcmJreTinkBc.zip](https://github.com/google/tink/files/2753082/EncryptionGcmJreTinkBc.zip)

**Comment by thaidn** [comment]
@java-crypto thanks for the report.

This is expected because StreamingAead is secure, but CipherInputStream/CipherOutputStream isn't.

To quote Daniel Bleichenbacher, CipherInputStream takes an existing encryption mode and simply allows to perform the same encryption with a stream interface. Tink uses encryption modes designed for streaming, i.e. authenticating blocks separately. So this isn't the same thing. When you read from StreamingAead, the returned data is _always_ authenticated. This is not the case with CipherOutputStream.

I think you can improve the performance of StreamingAead by increasing the block size. You're using 

`java
KeysetHandle keysetHandleGcm = KeysetHandle.generateNew(StreamingAeadKeyTemplates.AES256_GCM_HKDF_4KB);
`

Instead of 4KB, you might want to create a template with 1MB or even more, depending on how much memory you have.

**Comment by java-crypto** [comment]
Thanks for your response.

Regarding CipherIn/OutputStream: I searched a lot on the web but I could'nt find any working example for a File-Stream-based encryption/decryption **without** CipherIn/OutputStream - could you kindly share an example how to use Tink-StreamingAEAD without **Cipher**-Streams ?

Regarding performance: I don't believe that the perfomance can get significantly fastened by using a larger block size, especialy on decryption side. As my tests show the decryption time for a 5mb file compared to a 1mb file is factor 20 (should be around 5). The BouncyCastle decryption factor is between 2 or 3 and so better than expected 5 (and it uses the exact same stream construction).
As I tried to find a routine that can encrypt/decrypt realy large files (100mb and upwards) the decryption is unusable with JRE or Tink - thats why I asked for a change of (internal) implementation :-) Do you have an idea how to setup such an encryption/decryption routine?

Kind regards, Michael

**Comment by thaidn** [comment]
You're already using StreamingAead: https://github.com/java-crypto/TinkTest/blob/master/EncryptionGcmJreTinkBc.java#L229.

> I don't believe that the perfomance can get significantly fastened by using a larger block size, especialy on decryption side.

Have you actually tested with larger block sizes? It would help because it reduces the number of chunks and with that the overhead.

> As my tests show the decryption time for a 5mb file compared to a 1mb file is factor 20 (should be around 5). The BouncyCastle decryption factor is between 2 or 3 and so better than expected 5 (and it uses the exact same stream construction).

No, Bouncy Castle is using CipherInputStream, which is insecure because when you read from the encrypted stream, you wouldn't be able to detect modifications. Some references to learn more about this issue:

https://github.com/google/wycheproof/blob/master/java/com/google/security/wycheproof/testcases/CipherInputStreamTest.java#L171
http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/rev/cd617abcb69e
https://blog.heckel.xyz/2014/03/01/cipherinputstream-for-aead-modes-is-broken-in-jdk7-gcm/

**Comment by java-crypto** [comment]
Hi thaidn, Thanks for your response and links.

While working on a version without CipherInputStream I noticed that there is an error in my sourcecode. In the Tink-part the warmup uses Tink-methods but in the time measure part it uses the JRE-methods - **my fault and sorry**!

I setup new encryption-/decryption methods for JRE, Tink and BC avoiding CipherInputStreams and changed the method calls encryption old: "encryptWithGcmJre(filenamePlain, filenameEnc, password);" to new "encryptWithGcmTink(aead, filenamePlain, filenameEnc, aad);" and decryption old: "decryptWithGcmJre(filenameEnc, filenameDec, password);" to new "decryptWithGcmTink3(aead, filenameEnc, filenameDec, aad);".

Hier are the results of my tests and = WOW = the execution times are in the range of BouncyCastle, so everything looks fine !

Execution times for AES GCM with large files using JRE, TINK and BC Version 3
GCM Encryption / Decryption with JRE
Round	Filename	Enc	Dec
1	E:\t_1mb.dat	43	157
2	E:\t_2mb.dat	47	462
3	E:\t_3mb.dat	47	486
4	E:\t_4mb.dat	65	818
5	E:\t_5mb.dat	84	1235

GCM Encryption / Decryption with TINK
Round	Filename	Enc	Dec
1	E:\t_1mb.dat	28	15
2	E:\t_2mb.dat	47	38
3	E:\t_3mb.dat	62	60
4	E:\t_4mb.dat	79	83
5	E:\t_5mb.dat	91	100

GCM Encryption / Decryption with BC
Round	Filename	Enc	Dec
1	E:\t_1mb.dat	40	30
2	E:\t_2mb.dat	41	58
3	E:\t_3mb.dat	40	61
4	E:\t_4mb.dat	53	89
5	E:\t_5mb.dat	72	101
Execution times for AES GCM with large files using JRE, TINK and BC Version 3 ended

As the are no examples for encryption using channels - could you kindfully provide an file based channel example with SteamingAead ?

The sourcecode of my test is attached and on Github:
https://github.com/java-crypto/TinkTest/blob/master/EncryptionGcmJreTinkBcV3.java
[EncryptionGcmJreTinkBcV3.zip](https://github.com/google/tink/files/2765377/EncryptionGcmJreTinkBcV3.zip)

Kind regards, Michael

**Comment by thaidn** [comment]
The Channel-based APIs work very similar to the Stream-based APIs. You can find some sample snippets here: https://google.github.io/tink/javadoc/tink-android/1.2.0/com/google/crypto/tink/StreamingAead.html.
