### ISSUE TITLE
Java-HOWTO Guide is invalid

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [google/tink#206]
I am working on a small program, and as practice, I wanted to encrypt the users passwords.    
Following [the tutorial at the HOWTO guide](https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#symmetric-key-encryption), I got all the way to encrypt/decrypt.
However, when it asks for the function `Aead aead = keysetHandle.getPrimitive(Aead.class);`, keysetHandle does not implement the `getPrimitive()` method. keysetHandle is simply set the the keysetHandle that is loaded when the program starts.
I have created [a gist with the full class code](https://gist.github.com/xXXIMMATTHEWXXx/62dafaf4736808f6386d4c07e136a2d1). All help is appreciated!

**Comment by kelunik** [comment]
I had the same issue yesterday. You'll need to use the 1.2 branch to read the documentation, the master branch already uses a different API.

https://github.com/google/tink/blob/1.2/docs/JAVA-HOWTO.md

Depending on what you're doing, you probably want to hash passwords instead of / in addition to encrypting them, e.g. using BCrypt.

**Comment by xXXIMMATTHEWXXx** [comment]
@kelunik thanks, ill change versions.
