### ISSUE TITLE
Is there an equivalent class to AesGcmJce in Objective-C?

### ISSUE THREAD

**Issue by IrvingMg** [google/tink#238]
I want to implement a function to generate a key from user password and then encrypt and decrypt data with AES-GCM.  

Following [this recommendation](https://github.com/google/tink/issues/97#issuecomment-400750856) of @thaidn I implemented that function in Java using AesGcmJce Class to encrypt/decrypt but now, I want to use the equivalent class to encrypt/decrypt data with password based keys in Objective-C, however I haven't find an equivalent class to AesGcmJce in these language. 

Is there an AesGcmJce Class in Objective?

If there is not an equivalent class, what other approach I could use?

**Comment by przydatek** [comment]
AesGcmJce is in subtle, hence not a part of Tink's public API.  We do have in cc/subtle a C++ counterpart AesGcmBoringSSL, and although Obj-C is built on top of C++, AesGcmBoringSsl is not available directly in Obj-C (because it is not part of public API).  Still, you might enable access to it analogously to the way how Obj-C uses C++ public API.  Does it make sense?

**Comment by IrvingMg** [comment]
> AesGcmJce is in subtle, hence not a part of Tink's public API. We do have in cc/subtle a C++ counterpart AesGcmBoringSSL, and although Obj-C is built on top of C++, AesGcmBoringSsl is not available directly in Obj-C (because it is not part of public API). Still, you might enable access to it analogously to the way how Obj-C uses C++ public API. Does it make sense?

Got it. Thanks for answering!
