### ISSUE TITLE
Using Tink with Bazel's http_archive

### ISSUE THREAD

**Issue by derekargueta** [google/tink#306]
Hi, we're trying to add Tink as a dependency to Envoy but having issues. All the examples demonstrate how to use Bazel with Tink as the local repository, but there are no examples of using it as an external dependency.

We're trying to use something like:
```
http_archive(
    name = "tink_base",
    repo_mapping = {"@rapidjson": "@com_github_tencent_rapidjson"},
    sha256 = "ddc940b03d8e27343da612e78557c289781ad541fbdaed9c2a840943f5e92ed9",
    strip_prefix = "tink-599f1465fd8b503df65a545fcd23c564b91aa4e6",
    urls = ["https://github.com/google/tink/archive/599f1465fd8b503df65a545fcd23c564b91aa4e6.zip"],
)
```
but I'm not sure how to bind `@tink_cc`. Trying to reference `@tink_base` as the target, such as `"@tink_base//cc:tink_cc"` results in `no such package '@tink_base//config'`

**Comment by derekargueta** [comment]
Our solution for now is to use a git submodule then use `local_repository` like how the examples have, but it'd be great to get something working just using `http_archive` or `git_repository`

**Comment by tholenst** [comment]
We recently split the WORKSPACE files since we had big dependency issues. However, I am not confident that the state at head is stable. Given that you have problems, we surely should find a solution before we commit to it.

For now, you might want to stick to branch 1.3.0, where we only have a single WORKSPACE.

I'm also considering moving the WORKSPACE tink_base into it's own folder. However, I cannot see a way to download only a subdirectory on github, hence I don't think this helps you either.

**Comment by derekargueta** [comment]
@tholenst understood. We were initially on 1.3.0 but had to bump to a more recent SHA since the fix to make the `cleartext_keyset_handle` C++ target publicly visible wasn't until after the 1.3.0 release, and that's when we also picked up the multi-Workspace refactor since it's all [the same commit](https://github.com/google/tink/commit/9e7bb8f91c21ca133c850ecfbd948947d99b6503). We'll stick with a git submodule for now, but some documentation on how to consume Tink from an external C++ project would be greatly appreciated.

> I cannot see a way to download only a subdirectory on github, hence I don't think this helps you either

yeah that's the big dilemma. My understanding of Bazel external dependencies is that `http_archive` and `git_repository` bind that entire project to a single repository. I haven't found a way to bind to sub-workspaces.

**Comment by tholenst** [comment]
I want to try more today, but I think what should work is to strip the prefix.

I.e., you add an additional archive:

http_archive(
    name = "tink_cc",
    sha256 = "ddc940b03d8e27343da612e78557c289781ad541fbdaed9c2a840943f5e92ed9",
    strip_prefix = "tink-599f1465fd8b503df65a545fcd23c564b91aa4e6/cc",
    urls = ["https://github.com/google/tink/archive/599f1465fd8b503df65a545fcd23c564b91aa4e6.zip"],
)

Where I use the same values as you did above, but additionally we strip the directory cc. If that works, you probably want to specify the strings for "sha256" and "url" as normal constants in your WORKSPACE (like in python), so that you have a guarantee that they are always the same.

**Comment by thaidn** [comment]
Please comment if this is still a problem. Thanks.
