### ISSUE TITLE
Support IV for ChaCha20Poly1305 (Java API)

### ISSUE THREAD

**Issue by cmoine** [google/tink#307]
My team is developing a secure communication with an embedded application which uses WolfSSL.
WolfSSL defines clearly IV as parameter during encryption:
```c
wc_ChaCha20Poly1305_Encrypt (const byte inKey[CHACHA20_POLY1305_AEAD_KEYSIZE], const byte inIV[CHACHA20_POLY1305_AEAD_IV_SIZE], const byte *inAAD, const word32 inAADLen, const byte *inPlaintext, const word32 inPlaintextLen, byte *outCiphertext, byte outAuthTag[CHACHA20_POLY1305_AEAD_AUTHTAG_SIZE])
```
However, the Java API seems to not allow specifying an IV, here is my sample code (sorry it is Kotlin, not Java):
```kotlin
val keysetHandle = KeysetHandle.readNoSecret(key);
val aead = keysetHandle.getPrimitive(Aead::class.java)
aead.encrypt(inputData, addAuthData)
```
When searching in the source code of Tink I have found that some other key manager support IV, such as AesCtrKeyManager:
```java
private void validateParams(AesCtrParams params) throws GeneralSecurityException {
    if (params.getIvSize() < MIN_IV_SIZE_IN_BYTES || params.getIvSize() > 16) {
      throw new GeneralSecurityException("invalid IV size");
    }
  }
```

Am I missing something? Is there a specific reason for not supporting IV for ChaCha20Poly1305?
Thank you in advance!

**Comment by tholenst** [comment]
Tink does in general not allow access to the IV, since it is easy to have security problems by misuse. 

However, Tink stores the IV in the ciphertext. We will soon within days add a file WIRE-FORMAT.md where the ciphertext format is described. It is usually "IV || ciphertext || tag". You might be able to write it like this after the call to wc_ChaCha20Poly1305_Encrypt.
