### ISSUE TITLE
Be able to pass a SecureRandom for generating predictable PrivateKey

### ISSUE THREAD

**Issue by cmoine** [google/tink#309]
Of course, it is not for production purpose, since PrivateKey really need to be truly random.

But for tests, and prototyping reasons, it would be really nice to be able to generate PrivateKey by giving a SecureRandom (with kind "SHA1PRNG", and a given SEED, it becomes really predictable):
`X25519.generatePrivateKey(secureRandom)`
Every library such as BouncyCastle or https://github.com/signalapp/curve25519-java allow to pass a SecureRandom parameter: is there a specific reason for that?

**Comment by thaidn** [comment]
Hi there,

There's a reason for this, and it's security. The whole idea of Tink is not ask users for critical input. If we allow users to control the PRNG, sooner or later someone is going to use https://xkcd.com/221/ for production.

Instead of trying to generate a private key deterministically, I recommend generating a test key and reusing it for all tests.
