### ISSUE TITLE
Java class SigUtil public

### ISSUE THREAD

**Issue by gogit** [google/tink#340]
Make SigUtil public so it can be used from outside the package

**Comment by thaidn** [comment]
Hi there,

Can you tell us why you need it? It's package protected because we don't want external users to depend on too many internal implementation details.

**Comment by gogit** [comment]
https://github.com/gogit/contact-tracing/blob/master/src/test/java/com/thinktag/user/TinkDigitalSignature.java checkout the loading of pem using bouncycastle and tink

**Comment by thaidn** [comment]
We won't be able to open up SigUtil because we don't want users to depend on our protobuf messages which we want to keep as internal implementation details.

I have to admit that how Tink can read or write keys produced by other libraries is something we haven't got right in the library. We're actively rethinking this and will come up with a less clumsy solutions in the near future. Meanwhile, [1] is a good example for how to read PEM keys with Tink.

Hope that helps. Please reply if you have any other questions.

[1] https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/signature/SignaturePemKeysetReader.java
