### ISSUE TITLE
README: Clarify production safety of release candidates

### ISSUE THREAD

**Issue by leighmcculloch** [google/tink#371]
I see that 1.4.0-rc2 is the latest release and that it is a pre-release / release candidate. Initially I was unsure if this meant the release was recommended for use in production or environments protecting highly sensitive data.

I looked around in the docs and I was unable to find discussion about release candidates. I was able to find [this mailing list discussion from 2019](https://groups.google.com/d/msg/tink-users/PfqFyRdcRx8/up6xTm3BCAAJ) where @thaidn states that release candidates are safe for production and that any release candidate has already been in use in production within Google for months.

I think it could be helpful for newcomers to describe what the distinction between a release candidate and a release is for this project since the use of the term can vary. I am also not 100% clear on what the distinction is still in this project.

I think a good place for discussing that is probably in the README near the current status section.

cc @howardtw

**Comment by thaidn** [comment]
Thanks for your question.

Tink open source and Tink Google share the same code base, and Google products always use Tink at HEAD, that's why I said release candidates are stable and production-ready.

You're right that there is a clear distinction. Let me discuss with the team to see what we can do to make it clearer. Maybe we should just get rid of RC.

**Comment by thaidn** [comment]
Starting from 1.4.0, we'll no longer release candidates, only final.
