### ISSUE TITLE
Loading existing keysets in Python

### ISSUE THREAD

**Issue by Fi5t** [google/tink#394]
First of all, thank you for the ability to install Tink from PyPI!

I've started to play with the python version of Tink and decided to try save/load keysets for testing purposes. But the example from [Python HOW-TO](https://github.com/google/tink/blob/master/docs/PYTHON-HOWTO.md#loading-existing-keysets) describing this case is quite unclear for me. Can you help me to understand, where I can get `master_key_aead` from the following example:

```python
import tink

json_encrypted_keyset = ...
reader = tink.JsonKeysetReader(json_encrypted_keyset)
keyset_handle = tink.read_keyset_handle(reader, master_key_aead)
```

Maybe you can provide a more clear example.

**Comment by kste** [comment]
This example is for an encrypted keyset, so it depends on how to the keyset has been encrypted. For example if you use GCP you would do the following:

```python
import tink
from tink.integration import gcpkms

json_encrypted_keyset = ...
reader = tink.JsonKeysetReader(json_encrypted_keyset)

# Create the aead used for encrypting the keyset
key_uri = 'gcp-kms://projects/tink-examples/locations/global/keyRings/foo/cryptoKeys/bar'
gcp_client = gcpkms.GcpKmsClient(key_uri, 'path/to/credentials...')
master_key_aead = gcp_client.get_aead(key_uri)

keyset_handle = tink.read_keyset_handle(reader, master_key_aead)
```

**Comment by Fi5t** [comment]
@kste thank you for the exhaustive example! I have yet another question. I'm saving my keyset with as following:

```python
keyset_handle = tink.new_keyset_handle(aead.aead_key_templates.AES256_GCM)
aead_primitive = keyset_handle.primitive(aead.Aead)

with open('keyset.json', 'w') as keyset_file:
    keyset_handle.write(tink.JsonKeysetWriter(keyset_file), aead_primitive)
```

What I need to do to restore my keyset from a `keyset.json` file?

**Comment by kste** [comment]
In this case you would have to reconstruct the `aead_primitive` used for storing the encrypted keyset. For this you would have to store and load your `keyset_handle` created in the first line to restore it.

Now you kind of have the same problem again. Where to store this new keyset which is protecting the keyset in `keyset.json` :-). You can store it in cleartext, but that would not be recommended from a security perspective as it gives you full access to the `keyset.json` as well. That's why you typical would use some external KMS to protect your keyset to address this key management issue.

**Comment by Fi5t** [comment]
Yeah, I understand all the security flaws of this approach. I've just wanted to do it for the testing purposes. Ok, thank you for the explanation!
