### ISSUE TITLE
go: missing generated proto file for aes_ctr_hmac_streaming_go_proto

### ISSUE THREAD

**Issue by cuonglm** [google/tink#404]
With current [tip](https://github.com/google/tink/commit/2d16ed37d29c429a10b455550f6a817d8e2e9394):

```
$ go test ./...
go/streamingaead/aes_ctr_hmac_key_manager.go:27:2: cannot find package "github.com/google/tink/go/proto/aes_ctr_hmac_streaming_go_proto" in any of:
	/Users/cuonglm/sdk/go1.14.6/src/github.com/google/tink/go/proto/aes_ctr_hmac_streaming_go_proto (from $GOROOT)
	/Users/cuonglm/go/src/github.com/google/tink/go/proto/aes_ctr_hmac_streaming_go_proto (from $GOPATH)
can't load package: package github.com/google/tink/testing/go: found packages services (aead_service.go) and main (testing_server.go) in /Users/cuonglm/go/src/github.com/google/tink/testing/go
```

---

It will be great if there's instruction for how to geneated missing proto files.

**Comment by cuonglm** [comment]
@chuckx any instruction for how to generate the proto files?

**Comment by chuckx** [comment]
@cuonglm No, not yet.

Currently the proto files are generated _before_ migrating code from our internal repository to GitHub. I'm planning to revisit that approach so that it's based on the state of the project in git (i.e. post-publishing transformations). 

That will allow us to publicly document the process in addition to making it bit less complicated.

I have a few other tasks to tackle first, so I probably won't get to it for at least a couple weeks. I'll leave another comment on this issue to call attention to the commit(s) when I get to it.
