### ISSUE TITLE
Getting RSAPublicKey from keyset in Java

### ISSUE THREAD

**Issue by sparkedarkle** [google/tink#423]
I'm trying to get a `RSAPublicKey` object from a KeysetHandle, but it doesnt seem to be possible, partially because Android does not have built-in support for PKCS1, which is what the RSA based keyset templates in Tink are based on. Is there any built in helpers to do the necessary conversion?

**Comment by juergw** [comment]
Yes, this is currently not possible. But we are working on a new API to make this easier to do.

Note that usually it is preferable to not convert Tink keys into plain RSAPublicKey keys, because you will loose some metadata of the key, namely which algorithm to use it with. The user of the plain RSAPublicKey will then probably have to hard-code the algorithm and that makes it more difficult to change the algorithm in the future.

**Comment by juergw** [comment]
You should be able to do this in the main branch of Tink (and in the upcoming release):
- You first get the "Key" object from the Keyset using keysetHandle.getEntry(i).getKey().
- You then check that it is of the correct type RsaSsaPkcs1PublicKey, and cast it to that.
- Using this rsaSsaPkcs1PublicKey object, you can create a Java RSAPublicKey with:
    RSAPublicKey publicKey =
        (RSAPublicKey)
            keyFactory.generatePublic(
                new RSAPublicKeySpec(
                    rsaSsaPkcs1PublicKey.getModulus(), rsaSsaPkcs1PublicKey.getParameters().getPublicExponent()));

**Comment by juergw** [comment]
I have now added a test that shows how to do this:
https://github.com/google/tink/commit/fc420104fdd2a1e3404f2f3fa8536e45fd07ee57
