### ISSUE TITLE
Go : kms_envelope_aead: invalid ciphertext issue while loading Tinkey keyset into Tink code.

### ISSUE THREAD

**Issue by nikhilajayk** [google/tink#465]
**Describe the bug**

Using Tinkey, I've created a keyset. When i use Tink to load the keyset, it fails with an error  ` keyset.Handle: decryption failed: kms_envelope_aead: invalid ciphertext`

I am able to generate, encrypt and decrypt keys with AWS using Tinkey.
I am able to generate, encrypt and decrypt keys with AWS using Tink via the code.

What I'm unable to do is load a keyset created by Tinkey using Tink in the code and vice versa.

**To Reproduce**

Here is the Tinkey command that I've used.

`tinkey create-keyset --key-template AES256_GCM --out encrypt.json --master-key-uri aws-kms://arn:aws:kms:[my-cmk-details]`

This creates an encrypted keyset successfully.

Here is the Tink code that i use to read the keyset (mostly referred from the docs)

``` 
package main

import (
	"fmt"
	"log"
	"os"
	"github.com/google/tink/go/aead"
	"github.com/google/tink/go/core/registry"
	"github.com/google/tink/go/integration/awskms"
	"github.com/google/tink/go/keyset"
)

const (
	keyURI = "aws-kms://arn:aws:kms:[mykey]"
)

func main() {

	awsClient, err := awskms.NewClient(keyURI)
	if err != nil {
		log.Fatal(err)
	}
	registry.RegisterKMSClient(awsClient)

	backend, err := awsClient.GetAEAD(keyURI)
	if err != nil {
		log.Fatal(err)
	}
	masterKey := aead.NewKMSEnvelopeAEAD2(aead.AES256GCMKeyTemplate(), backend)

	// Reading the Keyset
	jsonKeyset, err := os.Open("./encrypt.json") 
	if err != nil {
		log.Fatal(err)
	}
	r := keyset.NewJSONReader(jsonKeyset)

	kh1, err := keyset.Read(r, masterKey)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(kh1.String)

}
 ```

**Expected behavior**

The Tink code should be able to read the keyset generated by Tinkey. 

**Error messages, stack traces, etc.**

keyset.Handle: decryption failed: kms_envelope_aead: invalid ciphertext

**Version information**

 - Language: (Tink - Go, Tinkey - Java )
 - Version - Latest stable

**Additional context**
I believe that I'm making some small mistake here, but I'm unable to figure it out. Any help would be really appreciated. 

Thanks for the support in advance!

**Comment by chuckx** [comment]
You're mixing two different implementations of the AEAD primitive. **The KMS integration that's part of `tinkey` is not the same thing as the "KMS Envelope" implementation within the library.**

When using "KMS Envelope", you end up with an encrypted copy of the DEK (data encryption key) embedded within the ciphertext. Then end result is that each encryption operation produces a unique DEK per ciphertext. With Tink, the creation and embedding of the DEK is handled automatically.

On the other hand, the `tinkey` KMS integration creates an encrypted keyset that's stored separate from any ciphertexts that may be subsequently produced using it. This keyset can be used for multiple encryption operations.

In order to access the keyset you created with `tinkey`, you use the `tink.AEAD` instance you get from calling `awsClient.GetAEAD()` in the straight forward manner:

```
package main

import (
        "fmt"
        "log"
        "os"
        "github.com/google/tink/go/integration/awskms"
        "github.com/google/tink/go/keyset"
)

const (
        keysetPath = "<path to file which contains the encrypted keyset produced by tinkey>"
        keyURI = "aws-kms://<ARN for the CMK>"
)

func main() {
        kmsClient, err := awskms.NewClient(keyURI)
        if err != nil {
                log.Fatal(err)
        }
        kmsAEAD, err := kmsClient.GetAEAD(keyURI)
        if err != nil {
                log.Fatal(err)
        }

        keysetFile, err := os.Open(keysetPath)
        if err != nil {
                log.Fatal(err)
        }
        keysetReader := keyset.NewJSONReader(keysetFile)
        keysetHandle, err := keyset.Read(keysetReader, kmsAEAD)
        if err != nil {
                log.Fatal(err)
        }

        fmt.Printf("%v\n", keysetHandle.String())
}
```

Here's the result of executing the above code using a keyset generated using an invocation of `tinkey` equivalent to yours:

```
$ go run decrypt_keyset.go
primary_key_id:416209333 key_info:<type_url:"type.googleapis.com/google.crypto.tink.AesGcmKey" status:ENABLED key_id:416209333 output_prefix_type:TINK >
```

A high-level description of Envelope Encryption is in the [Key Management HOW-TO](https://github.com/google/tink/blob/master/docs/KEY-MANAGEMENT.md#envelope-encryption), which also includes links to the AWS and GCP documentation for further reference. For low-level details, you can see how the KMS Envelope ciphertext is composed in [buildCipherText()](https://github.com/google/tink/blob/ca852750014fb65590585285e2ed7deeb04cb36a/go/aead/kms_envelope_aead.go#L130).

**Comment by nikhilajayk** [comment]
Hey @chuckx  This was exactly what I needed! Thanks a lot!
