### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by Kaiyiccc** [google/tink#476]
I just tested Tink with Python 3.9.1, it seems to work. Should it be added to the [how-to on Python](https://github.com/google/tink/blob/master/docs/PYTHON-HOWTO.md)?

```
Currently, this includes binary wheels for:

Linux: Python 3.7, Python 3.8
MacOs: Python 3.7, Python 3.8

```

**Comment by chuckx** [comment]
7e79f2e57e13f32bcaabbb5591c98d3398d0895d clarified the documentation a bit to distinguish between what's supported (e.g. Python 3.7+) and what we had published binary wheels for (3.7 and 3.8 on Linux and macOS).

I just published the Python packages for 1.6.0, which includes binary wheels for Python 3.9. I'll be following up with a documentation update to reflect this, as well as build/release script updates so that the 3.9 packages are built automatically for future releases.
