### ISSUE TITLE
Module 'tink' has no attribute 'daead' in Python3.8.2

### ISSUE THREAD

**Issue by dohyungp** [google/tink#498]
**Describe the bug**

When I trying get attribute `daead` from tink module, encounter AttributeError(aead is successfully got).

```py
>>> import tink
>>> module = getattr(tink, "aead")
>>> daead = getattr(tink, "daead")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tink' has no attribute 'daead'
```

```py
>>> tink.
tink.absolute_import               tink.BinaryKeysetWriter(           tink.division                      tink.KeysetHandle(                 tink.new_keyset_handle(            tink.read_keyset_handle(          
tink.aead                          tink.cc                            tink.JsonKeysetReader(             tink.KeysetReader(                 tink.print_function                tink.read_no_secret_keyset_handle(
tink.BinaryKeysetReader(           tink.core                          tink.JsonKeysetWriter(             tink.KeysetWriter(                 tink.proto                         tink.TinkError(                   
```

**Expected behavior**

```py
>>> daead = getattr(tink, "daead")
>>> daead.register()
# doesn't raise AttributeError
```

**Version information**

 - Language: Python3
 - Version: 1.5.0
 - Environment: Mac OS X(10.15.7), Python 3.8.2,  Tink 1.5.0

**Comment by chuckx** [comment]
You need to import the package for the DAEAD primitive:

```python
import tink
from tink import daead
```

Some background on the behavior you're seeing... when you only import the `tink` package, [the `aead` package happens to be transitively imported because it's used by the the `_keyset_handle` module](https://github.com/google/tink/blob/3993433abb873e8b198d41dc55d21ff4784cee56/python/tink/_keyset_handle.py#L29) (to facilitate encrypted keyset functionality).

However, for sake of consistency, it's best to always import the package of the primitives you're using. This is demonstrated in the examples (e.g. [DAEAD](https://github.com/google/tink/blob/3993433abb873e8b198d41dc55d21ff4784cee56/examples/python/deterministic_aead/deterministic_aead.py#L29-L31), [AEAD](https://github.com/google/tink/blob/3993433abb873e8b198d41dc55d21ff4784cee56/examples/python/aead/aead.py#L29-L31), etc.)
