### ISSUE TITLE
Can I use openssl decrypt the ciphertext encrypted by tink? 

### ISSUE THREAD

**Issue by scuhappy** [google/tink#503]
May I ask if I can use openssl to decrypt the text encrypt by tink? 
I found that , in Openssl AES_GCM_256 , the length of plaintext is same as ciphertext. but in tink , the length of ciphertext is 33 bytes longer than plaintext, So it seems that tink is incompatiable wiht other libraries. Am I right ? Thank you!

**Comment by atulluykx** [comment]
Note that in AES GCM, by definition the ciphertext must be longer than the plaintext because of the authentication tag. This is the case in openssl too: https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption

Tink's AES-GCM implementations abide by the NIST standards set out for GCM, and so its output should be decryptable by any library following the standards (in fact, in C++ Tink uses boringssl for its gcm implementation). 

Having said that, Tink by default does add a five byte prefix: https://github.com/google/tink/blob/master/docs/WIRE-FORMAT.md
If you don't want the prefix to be added, generate keys with OutputPrefixType set to RAW. See for example the Aes256GcmNoPrefix() function here:
https://github.com/google/tink/blob/master/cc/aead/aead_key_templates.h

**Comment by scuhappy** [comment]
Hi， 

   Thank you for your reply!
    I found that, in OpenSSL, the ciphertext and tag are output separately. but in tink, it is not. So I wonder if the cipher text in tink contains tag ? if so, how could I extract the tag ? Thank you!

**Comment by atulluykx** [comment]
In Tink the AEAD output is of the form
prefix || IV || ciphertext || tag
or, when there's no prefix,
IV || ciphertext || tag
(see https://github.com/google/tink/blob/master/docs/WIRE-FORMAT.md#crypto-formats ).

The prefix, IV, and tag lengths are fixed by the key template (see [1]), and what's called ciphertext above is the same length as the plaintext, so you can calculate where the tag starts in the output. As an example, if you use the Aes256Gcm key template, the tag size is 16 bytes and so you just need to get the last 16 bytes of the output.

[1] https://github.com/google/tink/blob/ab8670a9a971cff6834203d9b748dcb3f3c1510e/cc/aead/aead_key_templates.h#L63

**Comment by scuhappy** [comment]
Thank you very much ,my brother  ! !
