### ISSUE TITLE
No matching key found for the ciphertext in the stream

### ISSUE THREAD

**Issue by kirankjolly** [google/tink#517]
I am getting an exception while decrypting the encrypted file. Exception happening in the **decryptFile()** method. Line where exception happening is ` while (fileInputStream.read(buffer).also { read = it } != -1) {`

Full code below
**Encrypt**
```
fun encryptFile(source: File, destination: File, applicationContext: Context) {
    val mainKey = MasterKey.Builder(applicationContext, MasterKey.DEFAULT_MASTER_KEY_ALIAS)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()
    val encryptedFile = EncryptedFile.Builder(
        applicationContext,
        destination,
        mainKey,
        EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
    ).build()

    val fileOutputStream = encryptedFile.openFileOutput()
    val fileInputStream = FileInputStream(source)

    val buffer = ByteArray(1024)
    var read: Int
    while (fileInputStream.read(buffer).also { read = it } != -1) {
        fileOutputStream.write(buffer, 0, read)
    }

    fileInputStream.close()
    fileOutputStream.flush()
    fileOutputStream.close()
    source.delete()
    destination.renameTo(source)
}

```
**Decrypt**
```
fun decryptFile(source: File, destination: File, applicationContext: Context){
    val mainKey = MasterKey.Builder(applicationContext, MasterKey.DEFAULT_MASTER_KEY_ALIAS)
        .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
        .build()

    val encryptedFile = EncryptedFile.Builder(
        applicationContext,
        source,
        mainKey,
        EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
    ).build()

    val fileInputStream = encryptedFile.openFileInput()
    val fileOutputStream = FileOutputStream(destination)

    val buffer = ByteArray(1024)
    var read: Int

    while (fileInputStream.read(buffer).also { read = it } != -1) {
        fileOutputStream.write(buffer, 0, read)
    }

    fileInputStream.close()
    fileOutputStream.flush()
    fileOutputStream.close()
    source.delete()
    destination.renameTo(source)
}
```

I am using the alpha version of the security. Why I am using the alpha version of the security because the stable version is marked as deprecated

```
implementation("androidx.security:security-crypto:1.1.0-alpha03")
implementation("androidx.security:security-identity-credential:1.0.0-alpha02")
implementation("androidx.security:security-app-authenticator:1.0.0-alpha02")
```

I refer and follow the above code from https://developer.android.com/topic/security/best-practices#safe-data .
I can successfully run the code given in the above link. But when it comes to files instead of a string, my code not working

**Comment by kirankjolly** [comment]
@thaidn @chuckx  could you please help me

**Comment by chuckx** [comment]
Renaming the file is not supported by the `EncryptedFile` class.

In particular, when `newEncryptingStream()` and `newDecryptingStream()` are called, the file name is used as the `associatedData` argument. 

For reference, see the call sites here:

 * [`newEncryptingStream()` call in `EncryptedFile.openFileOutput()`](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/security/crypto/src/main/java/androidx/security/crypto/EncryptedFile.java?source=post_page---------------------------%2F&autodive=0%2F%2F%2F%2F%2F#228)
 * [`newDecryptingStream()` call in `EncryptedFile.openFileInput()`](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/security/crypto/src/main/java/androidx/security/crypto/EncryptedFile.java?source=post_page---------------------------%2F&autodive=0%2F%2F%2F%2F%2F#250)

In the context of AEAD, associated data is used to bind context to the ciphertext. A brief overview be find in [the Tink primitives documentation](https://github.com/google/tink/blob/master/docs/PRIMITIVES.md#authenticated-encryption-with-associated-data). This is all just FYI, since the choice about what associated data to use is defined in `androidx.security.crypto` implementation.
