### ISSUE TITLE
Java: telling apart secret KeysetHandle from public KeysetHandle

### ISSUE THREAD

**Issue by AnomalRoil** [google/tink#521]
I'm trying to load a key from disk, but I don't know before loading it if that's a private key or a public key.
I couldn't find the "proper" way of determining this using a `KeysetHandle` or even directly a Keyset.

As far as I can tell, 
```
key = CleartextKeysetHandle.read(JsonKeysetReader.withFile(keyFile))
```
is the way to read a key from a file. (I've seen the other methods and the possibility to encrypt key files, but I'm starting with an easy POC)

Next, we have a `KeysetHandle`, which has a `getPublicKeysetHandle` method that will throw a `java.security.GeneralSecurityException: The keyset contains a non-private key` when used on a public key...

So far the only reliable way I've found is the following (that's Kotlin, but the idea is clear):
```
     private var publicKey = try {
          secretKey?.getPublicKeysetHandle()
      } catch (e: GeneralSecurityException) {
          if (e.message == "The keyset contains a non-private key") {
              val temp = secretKey
              // this means we read a public key in the first place so erasing secret key
              secretKey = null
              temp 
          } else {
              null
          }   
     }
```

But my guess is that I'm missing something: that seems like the worst way of determining this.

How is one supposed to do that?

PS:
Also I've tried reading keys using the NoSecretKeysetHandle to make sure I get only the public key, but I'm getting a deprecation warning that doesn't match the documentation: 
> 'NoSecretKeysetHandle' is deprecated. Deprecated in Java

Is that normal?

**Comment by thaidn** [comment]
>I'm trying to load a key from disk, but I don't know before loading it if that's a private key or a public key.

This sounds strange. To use Tink, you must know whether you want to load a public key or a private key. Since Tink separates the private key API from the public key API (e.g., `HybridEncrypt` vs `HybridDecrypt`, `PublicKeySign` vs `PublicKeyVerify`), if you can't tell whether the key is private or public, you won't be able to use the correct API.

In general it shouldn't be hard to figure out the key type. If you want to verify a signature or encrypt a message, the key should be public. Otherwise it should be private. Armed with this information, you can then:

* Use [KeysetHandle.readNoSecret](https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/KeysetHandle.java#L131) to load public keysets. It will fail if the keyset contains private or secret key material.

* Use [KeysetHandle.read](https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/KeysetHandle.java#L114) or `ClearteextKeysetHandle` to load private keysets.

**Comment by AnomalRoil** [comment]
My problem isn't knowing what I want to do with the keys, my problem is that a user loading their secret key should be able to verify their own messages and create new ones, but a user loading a public key hasn't secret key material and so should only be able to verify messages.

And also being realistic: users are not always loading the right key at the right place and I want to make sure I'm not holding secret key material when I don't need it, but I also want to detect that as early as possible to be able to error out as soon as the wrong key is loaded in the wrong place.
That's easy with the `KeysetHandle.readNoSecret`, but more difficult the other way around, no?
I think that both `KeysetHandle.read` or `ClearteextKeysetHandle` can load public keyset without secret key material, no?
So a user expected to provide a secret key could still provide a public key instead and I would have a hard time determining that the problem come from there, no?

**Comment by thaidn** [comment]
I'm still not sure I completely understand the issue.

I imagine your app allows users to upload their key. There's a field for private key and another for public key. If the user provides a private key, they can sign and verify their own messages; otherwise they can verify only. As far as I can tell you want to know when the user supplies a wrong key. That is, they enter a public key in the private key's field, or vice versa. Is that correct?

If so, I think you can detect these errors by obtaining a keyset handle with `CleartextKeysetHanddle` and calling [getPrimitive()](https://github.com/google/tink/blob/master/java_src/src/main/java/com/google/crypto/tink/KeysetHandle.java#L339) to obtain the expected primitive. If `getPrimitive()` succeeds, you can store the primitive in memory and discard the keyset handle.
`getPrimitive()`, however, will fail if the keyset doesn't contain the right key type. That is, it will throw `GeneralSecurityException` if you attempted to obtain a `PublicKeySign` from a public key set or a `PublicKeyVerify` from a private keyset.

Does that solve your problem?

**Comment by AnomalRoil** [comment]
I feel like Tink is making key management (export, import, etc.) way more difficult than it ought to be. I don't like having to count on catching a generic `GeneralSecurityException` in order to determine my key type when importing a key. 
I'm guessing the goal is to force people to use dedicated KMS systems such as Vault?

Anyway, I guess we can consider this issue as being a request to add a `isPublicKey` and `isSecretKey` method, or maybe a `getKeyType` method instead to the `KeysetHandle` class.

**Comment by tholenst** [comment]
We do not plan to add a isSecretKey at the moment.

We have new serialization (in TinkKeysetProtoFormat) which should make this easier.
