### ISSUE TITLE
Error: cannot use ksw.Keyset

### ISSUE THREAD

**Issue by cvq** [google/tink#525]
To serialize keyset, i use ks, err := **proto.Marshal(ksw.Keyset)**
But there is a warning: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.
With **"google.golang.org/protobuf/proto"** there is an error: **cannot use ksw.Keyset** (variable of type *tink_go_proto.Keyset) as protoreflect.ProtoMessage value in argument to proto.Marshal: missing method ProtoReflect

Please help to fix.

**Comment by thaidn** [comment]
I believe this is a known issue. @chuckx thoughts?

BTW can you tell us why you want to serialize keysets? Does https://github.com/google/tink/blob/master/go/insecurecleartextkeyset/insecurecleartextkeyset.go#L60 work for you?

**Comment by cvq** [comment]
I want to exchange private key for Decryption later (Hybrid).
I think your link is that i have to try.
Thank you.

**Comment by chuckx** [comment]
In the context of Hybrid encryption, the private key material should be kept on the encrypting side. There should be no need to serialize it. **_Instead, you should extract the public key material and serialize that_**. 

Serializing private key material in the clear should be avoided, which is why that functionality is in package named `insecureclearttextkeyset` and contains warning against it's usage.

Assuming that `ksw.Keyset` is a `keyset.Handle` instance that contains private key material, you'll want to use [`Handle.Public()`](https://pkg.go.dev/github.com/google/tink/go@v1.6.0/keyset#Handle.Public) to create a new `keyset.Handle` instance which contains only the corresponding public keys.

Then you can use [`Handle.WriteWithNoSecrets()`](https://pkg.go.dev/github.com/google/tink/go@v1.6.0/keyset#Handle.WriteWithNoSecrets) to serialize an unencrypted copy of the keyset. This approach avoids needing to use the `insecurecleartextkeyset` package.

---

Regarding the warning message, it's more of a call to action for us, the maintainers of Tink, as opposed to something that users of the library need to do something about. I'm working on a set of updates to the Go protobuf code which will remove that warning. The updates should probably land before the next minor release. In any case, the issue is being tracked in #439.

**Comment by cvq** [comment]
Thank you **chuckx**
