### ISSUE TITLE
Any plans to support CloudHSM v2 (AWS)?

### ISSUE THREAD

**Issue by ebcodes** [google/tink#60]
https://docs.aws.amazon.com/cloudhsm/latest/userguide/java-library.html

Any plans to support it as another KMS provider? Only asking because I'm currently evaluating frameworks that would make integration with CloudHSM v2 easier and tink seems like a decent choice to try out.

If there are no plans, I'll consider adding a PR once the work is completed, but figured I'd ask first.

Thanks!

**Comment by thaidn** [comment]
Hi there,

The KmsClient interface is limited as it only allows obtaining an Aead primitive from the KMS provider. This Aead can be used to wrap keysets or secrets. If this is all you need, we can easily add support for CloudHSM. Of course, if you can send a PR it'll be most welcome!

If you also need key generation, it'll be more difficult because we'll need to extend the KmsClient to add such functionality.

**Comment by przydatek** [comment]
Closing for now, feel free to reopen if needed.
