### ISSUE TITLE
Windows OS Support

### ISSUE THREAD

**Issue by Kwanghyuk-Kim** [google/tink#713]
**Help us help you**

According to below issue and current-status on github, windows os doesn't seem to be supported by tink yet officially.

reference 1. https://github.com/google/tink/issues/502
reference 2. https://github.com/google/tink#current-status

Doesn't tink support windows os yet for below languages ? is it true?
- java
  . in fact, java version seems to work on the windows os according to my test.
  . wasn't tink java supported either?
- c++
- Go

Do you have any special reason that tink will not support windows os yet?

**Comment by morambro** [comment]
Hi @Kwanghyuk-Kim 

> **Help us help you**
> 
> According to below issue and current-status on github, windows os doesn't seem to be supported by tink yet officially.
> 
> reference 1. #502 reference 2. https://github.com/google/tink#current-status
> 
> Doesn't tink support windows os yet for below languages ? is it true?
> 
> * java
>   . in fact, java version seems to work on the windows os according to my test.
>   . wasn't tink java supported either?
> * c++
> * Go
> 
> Do you have any special reason that tink will not support windows os yet?

Windows support is currently not a high priority for the team; we recently added some support for C++ in v2.0.0 (https://github.com/tink-crypto/tink-cc/releases/tag/v2.0.0). Other implementations *may* work on Windows, but we don't have CI coverage testing this at the moment.

**Comment by Kwanghyuk-Kim** [comment]
@morambro 

thx for the answer. :)

> Windows support is currently not a high priority for the team; 
Is there any milestone for supporting windows os?
although priority of it will not be high, I would like to roughly know the time line for windows support. :)

**Comment by davidkhala** [comment]
+1 and look for below language support:
- python

**Comment by morambro** [comment]
Hi @davidkhala, since https://github.com/tink-crypto/tink-py/commit/5b03c501f9e09694ca803cb1d20f258851fadc7a, it should be possible to `python3 -m pip install .` from tink-py's root on MS Windows. It requires Windows Server >= 2019 on X86_64, Visual Studio 2019 >= 16.10 and `protoc >=25.2` installed. This should be included in the next Tink Python release.

I am going to close this issue. In case you have other requests/feedback, please open a new issue in the appropriate repo(s) in https://github.com/tink-crypto.
