### ISSUE TITLE
Possible timing problem with Bytes.equal()

### ISSUE THREAD

**Issue by SalusaSecondus** [google/tink#73]
Unfortunately I do not have the references in front of me to link (I'll try to find them), however I have absolutely seen evidence and graphs which imply that the standard constant-time byte-comparison algorithm when written in Java is not actually constant time in the JVM and may produce a usable signal.

Out of an excess of caution, I would recommend replacing `Bytes.equal()` with an implementation which first calculates the HMAC of each input value (under a random key) and then compares the MACs for equality. (This second test may or may not be constant time.)  It is a performance trade off if you'd prefer to generate a random HMAC key once per application (as a `private static final`) or freshly for each comparison.

**Comment by thaidn** [comment]
Bytes.equal is mostly used to validate MAC, thus we're already doing what you're suggesting, right?

**Comment by SalusaSecondus** [comment]
No. The problem is that one of the MACs is attacker controlled.  So, if one value is unknown (the correct MAC calculated under a secret key) and the other is attacker controlled, then if `Bytes.equal()` has a timing signal, an attacker can use this to guess the secret MAC. (This is why you are using this standard constant-time algorithm.)

Unfortunately, the JVM and JIT does terrible things to constant time algorithms and can break them horribly.  By calculating a MAC under a random key of the values and then comparing those MACs, even if the algorithm isn't constant time, the attacker has no way of knowing what bytes are being compared to what bytes and cannot execute the attack.

NCC Group wrote about an extremely similar defense they call [Double HMAC Verification](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/february/double-hmac-verification/). I prefer my proposed modification because it doesn't require knowledge of the HMAC key (and may be applied to things other than HMACs) and because it is even more randomized than reusing a key multiple times dor the comparison.

**Comment by thaidn** [comment]
Ah I now see what you meant.


Not sure we need to use double HMAC. Why isn't applying a round of SHA256 enough?

**Comment by katrielalex** [comment]
I have no idea about JVM and constant time algorithms but I don't think a round of SHA256 would be enough, because the attacker could also compute it and would thus know what bytes are being compared. Computing a MAC under a (secret) random key does not reveal that to the attacker.

**Comment by thaidn** [comment]
Unless there's a cleverer attack that I'm unaware of, the timing side channel attack allows recovering the secret HMAC value byte-by-byte. This attack is thwarted if Bytes.equal(s1, s2) compares SHA256(s1) with SHA256(s2). Yes, the adversary knows what bytes are being compared, but that's not enough because they need to find a pre-image that hashes to those bytes.

More concretely, they know SHA256(s1) and they can use the timing side channel to figure out the first byte of SHA256(s2). Now what? They need to find s1' such that its first byte matches the first byte of SHA256(s1) and its second byte matches the second byte of SHA256(s2). Before long, the adversary has to reverse SHA256.

**Comment by thaidn** [comment]
Unless there's a cleverer attack that I'm unaware of, the timing side channel attack allows recovering the secret HMAC value byte-by-byte. This attack is thwarted if Bytes.equal(s1, s2) compares SHA256(s1) with SHA256(s2). Yes, the adversary knows what bytes are being compared, but that's not enough because they need to find a pre-image that hashes to those bytes.

More concretely, they know SHA256(s1) and they can use the timing side channel to figure out the first byte of SHA256(s2). Now what? They need to find s1' such that its first byte matches the first byte of SHA256(s1) and its second byte matches the second byte of SHA256(s2). Before long, the adversary has to reverse SHA256.

**Comment by bleichen** [comment]
Thai,

I'm just seeing your e-mail.
If you want us to participate in this question, then you have to give us
some context about what the question actually is,
or give a link to some previous discussions.

**Comment by hillbrad** [comment]
How I feel about that blog being cited to @thaidn and @bleichen : https://www.theonion.com/bush-finds-error-in-fermilab-calculations-1819566086

(Is is overkill, was intended as advice for naive developers, and it does weaken the HMAC verification against brute force guessing to the collision probability of the hash function.)

**Comment by SalusaSecondus** [comment]
@hillbrad Thank you. I'm also going to try to track down (and then make public) the other data I found. However until I can find something more solid, we should probably consider this issue closed.

**Comment by thaidn** [comment]
Thanks folks. Closing this bug, but please feel free to reopen once you've gathered more data.

**Comment by tarcieri** [comment]
It should be possible to use the [PrintAssembly](https://wiki.openjdk.java.net/display/HotSpot/PrintAssembly) command line option for the JVM to have HotSpot emit the generated assembly, which can then be verified for constant-time operation on an architecture-by-architecture basis.
